### ISSUE TITLE
500 status code on all gateway

### ISSUE THREAD

**Issue by tmfadhlul** [koutsoumposval/laravel-microservices#2]
i have follow the instruction step by step but still stuck on internal server error, pls help

**Comment by mazeeblanke** [comment]
@tmfadhlul were you able to get it working ?

**Comment by koutsoumposval** [comment]
I have updated documentation and configuration. You can now try again! Let me know if you managed to have it working

**Comment by mazeeblanke** [comment]
@koutsoumposval Hi, i am still having having issues setting it up. I am on a windows machine. i noticed that the files are not 'synced' with the container when i use docker-machine. which leads to errors like: 

```    | AH00112: Warning: DocumentRoot [/var/www/html] does not exist```

**Comment by mazeeblanke** [comment]
@koutsoumposval I have been on the issue since yesterday, please can you point me in the right direction ?

**Comment by koutsoumposval** [comment]
It seems that there is something wrong with the volume mounting or the build of the image. Unfortunately I am working on Linux environment and I don't have an easy answer/solution to your problem but I would recommend to remove and create step by step your docker-machine.

Anyway, this issue is regarding something else and has nothing to do with the problem that you are facing. This problem was happening because composer dependencies were not installed on each service, something that I added documentation for.

**Comment by mazeeblanke** [comment]
@koutsoumposval okay thank you, i will follow the updated steps and see if it works.

**Comment by mazeeblanke** [comment]
@koutsoumposval It is not still working, please what will you suggest as alternative to using  docker-machine, because that's is what is causing the problem.

**Comment by koutsoumposval** [comment]
You can try with the native [docker app for Windows]( https://docs.docker.com/docker-for-windows/)

**Comment by mazeeblanke** [comment]
@koutsoumposval Thanks, I am actually using docker for windows. I am thinking of trying kubernetes
